
// Generated from ./SysMLv2.g4 by ANTLR 4.13.2

#pragma once


#include "antlr4-runtime.h"




class  SysMLv2Lexer : public antlr4::Lexer {
public:
  enum {
    T__0 = 1, CROSSES = 2, KEYWORD_ACCEPT = 3, KEYWORD_ACTION = 4, KEYWORD_ACTOR = 5, 
    KEYWORD_AFTER = 6, KEYWORD_ALIAS = 7, KEYWORD_ALLOCATE = 8, KEYWORD_ALLOCATION = 9, 
    KEYWORD_ANALYSIS = 10, KEYWORD_ASSIGN = 11, KEYWORD_ASSERT = 12, KEYWORD_ASSUME = 13, 
    KEYWORD_AT = 14, KEYWORD_ATTRIBUTE = 15, KEYWORD_BIND = 16, KEYWORD_BLOCK = 17, 
    KEYWORD_CALC = 18, KEYWORD_CASE = 19, KEYWORD_CONCERN = 20, KEYWORD_CONNECT = 21, 
    KEYWORD_CONNECTION = 22, KEYWORD_CONSTRAINT = 23, KEYWORD_CROSSES = 24, 
    KEYWORD_DECIDE = 25, KEYWORD_DEF = 26, KEYWORD_DEFINED = 27, KEYWORD_DERIVED = 28, 
    KEYWORD_DO = 29, KEYWORD_ENTRY = 30, KEYWORD_ENUM = 31, KEYWORD_EVENT = 32, 
    KEYWORD_EXHIBIT = 33, KEYWORD_EXIT = 34, KEYWORD_EXPOSE = 35, KEYWORD_FORK = 36, 
    KEYWORD_FRAME = 37, KEYWORD_GUARD = 38, KEYWORD_INCLUDE = 39, KEYWORD_INDIVIDIAL = 40, 
    KEYWORD_INTERFACE = 41, KEYWORD_ITEM = 42, KEYWORD_JOIN = 43, KEYWORD_LOOP = 44, 
    KEYWORD_MERGE = 45, KEYWORD_MESSAGE = 46, KEYWORD_NONUNIQUE = 47, KEYWORD_OBJECTIVE = 48, 
    KEYWORD_OCCURRENCE = 49, KEYWORD_PARALLEL = 50, KEYWORD_PART = 51, KEYWORD_PERFORM = 52, 
    KEYWORD_PORT = 53, KEYWORD_REF = 54, KEYWORD_REFERENCES = 55, KEYWORD_RENDER = 56, 
    KEYWORD_RENDERING = 57, KEYWORD_REQUIRE = 58, KEYWORD_REQUIREMENT = 59, 
    KEYWORD_SATISFY = 60, KEYWORD_SEND = 61, KEYWORD_SNAPSHOT = 62, KEYWORD_STAKEHOLDER = 63, 
    KEYWORD_STATE = 64, KEYWORD_SUBJECT = 65, KEYWORD_TERMINATE = 66, KEYWORD_TIMESLICE = 67, 
    KEYWORD_TRANSISTION = 68, KEYWORD_TRIGGER = 69, KEYWORD_UNTIL = 70, 
    KEYWORD_USE = 71, KEYWORD_VARIANT = 72, KEYWORD_VARIATION = 73, KEYWORD_VERIFICATION = 74, 
    KEYWORD_VERIFY = 75, KEYWORD_VIA = 76, KEYWORD_VIEW = 77, KEYWORD_VIEWPOINT = 78, 
    KEYWORD_WHEN = 79, KEYWORD_WHILE = 80, SYMBOL_CROSSES = 81, MULTIPLICITY_PART_ELEMENTS = 82, 
    TYPED_BY = 83, SPECIALIZES = 84, SUBSETS = 85, REFERENCES = 86, REDEFINES = 87, 
    CONJUNGATES = 88, KEYWORD_ABOUT = 89, KEYWORD_ABSTRACT = 90, KEYWORD_ALL = 91, 
    KEYWORD_AND = 92, KEYWORD_AS = 93, KEYWORD_ASSOC = 94, KEYWORD_BEHAVIOR = 95, 
    KEYWORD_BINDING = 96, KEYWORD_BOOL = 97, KEYWORD_BY = 98, KEYWORD_CHAINS = 99, 
    KEYWORD_CLASS = 100, KEYWORD_CLASSIFIER = 101, KEYWORD_COMMENT = 102, 
    KEYWORD_COMPOSITE = 103, KEYWORD_CONJUGATE = 104, KEYWORD_CONJUGATES = 105, 
    KEYWORD_CONJUGATION = 106, KEYWORD_CONNECTOR = 107, KEYWORD_DATATYPE = 108, 
    KEYWORD_DEFAULT = 109, KEYWORD_DEPENDENCY = 110, KEYWORD_DIFFERENCES = 111, 
    KEYWORD_DISJOINING = 112, KEYWORD_DISJOINT = 113, KEYWORD_DOC = 114, 
    KEYWORD_ELSE = 115, KEYWORD_END = 116, KEYWORD_EXPR = 117, KEYWORD_FALSE = 118, 
    KEYWORD_FEATURE = 119, KEYWORD_FEATURED = 120, KEYWORD_FEATURING = 121, 
    KEYWORD_FILTER = 122, KEYWORD_FIRST = 123, KEYWORD_FLOW = 124, KEYWORD_FOR = 125, 
    KEYWORD_FROM = 126, KEYWORD_FUNCTION = 127, KEYWORD_HASTYPE = 128, KEYWORD_IF = 129, 
    KEYWORD_INTERSECTS = 130, KEYWORD_IMPLIES = 131, KEYWORD_IMPORT = 132, 
    KEYWORD_IN = 133, KEYWORD_INOUT = 134, KEYWORD_INTERACTION = 135, KEYWORD_INV = 136, 
    KEYWORD_INVERSE = 137, KEYWORD_INVERTING = 138, KEYWORD_ISTYPE = 139, 
    KEYWORD_LANGUAGE = 140, KEYWORD_MEMBER = 141, KEYWORD_METACLASS = 142, 
    KEYWORD_METADATA = 143, KEYWORD_MULTIPLICITY = 144, KEYWORD_NAMESPACE = 145, 
    KEYWORD_NOT = 146, KEYWORD_NULL = 147, KEYWORD_OF = 148, KEYWORD_OR = 149, 
    KEYWORD_ORDERED = 150, KEYWORD_OUT = 151, KEYWORD_PACKAGE = 152, KEYWORD_PORTION = 153, 
    KEYWORD_PREDICATE = 154, KEYWORD_PRIVATE = 155, KEYWORD_PROTECTED = 156, 
    KEYWORD_PUBLIC = 157, KEYWORD_READONLY = 158, KEYWORD_REDEFINES = 159, 
    KEYWORD_REDEFINITION = 160, KEYWORD_REP = 161, KEYWORD_RETURN = 162, 
    KEYWORD_SPECILIZATION = 163, KEYWORD_SPECIALIZES = 164, KEYWORD_STEP = 165, 
    KEYWORD_STRUCT = 166, KEYWORD_SUBCLASSIFIER = 167, KEYWORD_SUBSET = 168, 
    KEYWORD_SUBSETS = 169, KEYWORD_SUBTYPE = 170, KEYWORD_SUCCSESSION = 171, 
    KEYWORD_THEN = 172, KEYWORD_TO = 173, KEYWORD_TRUE = 174, KEYWORD_TYPE = 175, 
    KEYWORD_TYPED = 176, KEYWORD_TYPING = 177, KEYWORD_UNIONS = 178, KEYWORD_XOR = 179, 
    KEYWORD_VAR = 180, KEYWORD_LOCALE = 181, KEYWORD_STANDARD = 182, KEYWORD_LIBRARY = 183, 
    KEYWORD_CONSTANT = 184, SINGLE_LINE_NOTE = 185, MULTI_LINE_NOTE = 186, 
    REGULAR_COMMENT = 187, SYMBOL_COMMENT_BLOCK_START = 188, SYMBOL_NOTE_BLOCK_START = 189, 
    SYMBOL_COMMENT_BLOCK_END = 190, SYMBOL_STATEMENT_DELIMITER = 191, SYMBOL_STAR = 192, 
    SYMBOL_NAMESPACE_SUBSET = 193, SYMBOL_TYPED_BY = 194, SYMBOL_SPECIALIZES = 195, 
    SYMBOL_REFERENCES = 196, SYMBOL_REDEFINES = 197, SYMBOL_CONJUNGATES = 198, 
    SYMBOL_ROUND_BRACKET_OPEN = 199, SYMBOL_ROUND_BRACKET_CLOSE = 200, SYMBOL_CURLY_BRACKET_OPEN = 201, 
    SYMBOL_CURLY_BRACKET_CLOSE = 202, SYMBOL_SQUARE_BRACKET_OPEN = 203, 
    SYMBOL_SQUARE_BRACKET_CLOSE = 204, SYMBOL_COMMA = 205, SYMBOL_AT = 206, 
    SYMBOL_HASHTAG = 207, SYMBOL_MOD = 208, SYMBOL_AND = 209, SYMBOL_UPPER = 210, 
    SYMBOL_VERTICAL_LINE = 211, SYMBOL_DOUBLE_STAR = 212, SYMBOL_PLUS = 213, 
    SYMBOL_MINUS = 214, SYMBOL_SLASH = 215, SYMBOL_ARROOW = 216, SYMBOL_DOT = 217, 
    SYMBOL_DDOT = 218, SYMBOL_SMALLER = 219, SYMBOL_SMALLER_EQUAL = 220, 
    SYMBOL_ASSIGN = 221, SYMBOL_DEF_ASSIGN = 222, SYMBOL_EQUALS = 223, SYMBOL_IFF_EQUALS = 224, 
    SYMBOL_NOT_EQUALS = 225, SYMBOL_IFF_NOT_EQUALS = 226, SYMBOL_GREATER = 227, 
    SYMBOL_GREATER_EQUALS = 228, SYMBOL_QUESTION = 229, SYMBOL_DQUESTION = 230, 
    SYMBOL_DOT_QUESTION = 231, NAME = 232, BASIC_NAME = 233, UNRESTRICTED_NAME = 234, 
    DECIMAL_VALUE = 235, EXPONENTIAL_VALUE = 236, STRING_VALUE = 237, WS = 238
  };

  explicit SysMLv2Lexer(antlr4::CharStream *input);

  ~SysMLv2Lexer() override;


  std::string getGrammarFileName() const override;

  const std::vector<std::string>& getRuleNames() const override;

  const std::vector<std::string>& getChannelNames() const override;

  const std::vector<std::string>& getModeNames() const override;

  const antlr4::dfa::Vocabulary& getVocabulary() const override;

  antlr4::atn::SerializedATNView getSerializedATN() const override;

  const antlr4::atn::ATN& getATN() const override;

  // By default the static state used to implement the lexer is lazily initialized during the first
  // call to the constructor. You can call this function if you wish to initialize the static state
  // ahead of time.
  static void initialize();

private:

  // Individual action functions triggered by action() above.

  // Individual semantic predicate functions triggered by sempred() above.

};

