//
// Created by moritzh on 20.07.23.
//

#ifndef DIGITALTWINKI4BOARDNET_DIRECTCONNECTIONMANAGER_H
#define DIGITALTWINKI4BOARDNET_DIRECTCONNECTIONMANAGER_H


class DirectConnectionManager {

};


#endif //DIGITALTWINKI4BOARDNET_DIRECTCONNECTIONMANAGER_H
