//
// Created by moritzh on 19.05.23.
//

#ifndef ENERGYPROBEDRIVER_ENERGY_PROBE_DRIVER_GLOBAL_H
#define ENERGYPROBEDRIVER_ENERGY_PROBE_DRIVER_GLOBAL_H

#ifdef _WIN32
#define DIGITWESTER_EXPORT __declspec(dllexport)
#else
#define DIGITWESTER_EXPORT
#endif


#endif //ENERGYPROBEDRIVER_ENERGY_PROBE_DRIVER_GLOBAL_H
