//
// Created by Moritz Herzog on 09.01.24.
//

#ifndef DIGITALTWIN_BASEDIGITALTWININSTANCEMANAGER_H
#define DIGITALTWIN_BASEDIGITALTWININSTANCEMANAGER_H


class BaseDigitalTwinInstanceManager {

};


#endif //DIGITALTWIN_BASEDIGITALTWININSTANCEMANAGER_H
