//
// Created by Moritz Herzog on 19.02.24.
//
//---------------------------------------------------------
// Constants, Definitions, Pragmas
//---------------------------------------------------------
#pragma once
//---------------------------------------------------------
// External Classes
//---------------------------------------------------------
#include <string>
#include <vector>
//---------------------------------------------------------
// Internal Classes
//---------------------------------------------------------
#include <chrono>

#include "../cps_base_global.h"
//---------------------------------------------------------
// Forwarding
//---------------------------------------------------------


namespace CPSBASELIB::STD_EXTENTION {
    /**
     * This class extends the standard libraries abilities to work with strings.
     *
     * @class StringExtention
     * @version 1.1
     * @author Moritz Herzog <herzogm@rptu.de>
     */
    class CPSBASELIB_EXPORT StringExtention {
    public:
        /**
         * Splits a string with another string as the delimiter. If the delimiter is not contained, the string is not
         * split and will be fully contained in index 0, also the length of the vector is 1.
         * @param contentString The string with the content, that will be split.
         * @param delimiter The char that is searched for within the content string parameter.
         * @return A string array that is generated by splitting the string.
         */
        static std::vector<std::string> splitString(std::string contentString, char delimiter);

        /**
         * Transforms a string to a string with all lower characters.
         * @param string The given string with possible uppercase letters.
         * @return The given string wil all lowercase characters.
         */
        static std::string toLower(std::string string);

        /**
         * Generates string from timepoint.
         * @param timepoint The given timepoint as a std::chrono::time_point<std::chrono::system_clock>.
         * @return A std::string of the given timepoint.
         */
        static std::string timepointToString(std::chrono::time_point<std::chrono::system_clock> timepoint);

        /**
         * Parses the given time point from a given string.
         * @param timepointString The timepoint given as a String
         * @return The timepoint as a std::chrono::time_point<std::chrono::system_clock>
         */
        static std::chrono::time_point<std::chrono::system_clock> timepointFromString(std::string timepointString);

    };
}