//
// Created by Moritz Herzog on 19.02.24.
//

#include <gtest/gtest.h>
#include <typeinfo>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/lexical_cast.hpp>
#include <SysMLv2Standard/entities/Identification.h>
#include <SysMLv2Standard/entities/DataIdentity.h>
#include <SysMLv2Standard/entities/Project.h>
#include <SysMLv2Standard/entities/Branch.h>
#include <SysMLv2Standard/entities/Element.h>
#include <SysMLv2Standard/SysMLv2Deserializer.h>

/**
 * Tests the serilization of the object containing a valid uuid.
 */
TEST(TestSerilization,TestSerilizationItentityNonEmptyId) {
    std::string jsonString = "{\n"
                             "  \"@id\": \"781f769c-b7f8-4b38-a732-592fda775626\"\n"
                             "}";
    SysMLv2::Entities::DataIdentity identity = SysMLv2::Entities::DataIdentity(boost::uuids::string_generator()("781f769c-b7f8-4b38-a732-592fda775626"));
    EXPECT_EQ(jsonString,identity.serializeToJson());
}

/**
 * Tests Se
 */
TEST(TestDeserialization, TestDeserializationIdentity){
    std::string jsonString = "{\n"
                             "  \"@id\": \"781f769c-b7f8-4b38-a732-592fda775626\"\n"
                             "}";
    SysMLv2::Entities::DataIdentity identity = SysMLv2::Entities::DataIdentity("{\"@id\":\"781f769c-b7f8-4b38-a732-592fda775626\"}");
    EXPECT_EQ(jsonString,identity.serializeToJson());
    EXPECT_EQ(boost::uuids::string_generator()("781f769c-b7f8-4b38-a732-592fda775626"),identity.getId());
}

TEST(TestSerilization, TestSerilizationProjectWithStringOfBackend) {
    SysMLv2::Entities::Project project = SysMLv2::Entities::Project("  {\n"
                                                                    "    \"@id\": \"3fa85f64-5717-4562-b3fc-2c963f66afa6\",\n"
                                                                    "    \"@type\": \"string\",\n"
                                                                    "    \"name\": \"string\",\n"
                                                                    "    \"description\": \"string\",\n"
                                                                    "    \"defaultBranch\": {\n"
                                                                    "      \"@id\": \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"\n"
                                                                    "    },\n"
                                                                    "    \"created\": \"2024-02-22T08:58:57.343Z\"\n"
                                                                    "  }");

    EXPECT_EQ(boost::uuids::string_generator()("3fa85f64-5717-4562-b3fc-2c963f66afa6"),project.getId());
    EXPECT_EQ("string", project.getType());
    EXPECT_EQ("string", project.getName());
    EXPECT_EQ("string", project.getDescription());

    //EXPECT_TRUE(SysMLv2::Entities::Branch("{ \"@id\": \"3fa85f64-5717-4562-b3fc-2c963f66afa6\" }") == *(project.getDefaultBranch()));
}

TEST(TestDeserialization, TestDeserilizationCrashIssueWithout) {
    try {
        std::string jsonString = "[{\"id\":\"e1a5a414-b6c8-483d-8e90-d6ec46dbc590\",\"name\":\"ScalarValues\",\"description\":\"Pre-loaded project ScalarValues\",\"defaultId\":\"e2706ccd-6f92-4693-9c0a-207ac23f3d8d\",\"commitIDs\":[\"e2706ccd-6f92-4693-9c0a-207ac23f3d8d\"],\"headIDs\":[\"e2706ccd-6f92-4693-9c0a-207ac23f3d8d\"]},{\"id\":\"7fae8873-377c-4cc6-bf16-e8b8eaf2901f\",\"name\":\"ISO26262\",\"description\":\"Pre-loaded project ISO26262\",\"defaultId\":\"883c3982-3236-4822-adcb-64dacc3ac618\",\"commitIDs\":[\"883c3982-3236-4822-adcb-64dacc3ac618\"],\"headIDs\":[\"883c3982-3236-4822-adcb-64dacc3ac618\"]},{\"id\":\"93d9c988-287b-4650-9c98-a6479d79df62\",\"name\":\"SI\",\"description\":\"Pre-loaded project SI\",\"defaultId\":\"becdb5cb-a648-431a-b418-efa9d92e1a1d\",\"commitIDs\":[\"becdb5cb-a648-431a-b418-efa9d92e1a1d\"],\"headIDs\":[\"becdb5cb-a648-431a-b418-efa9d92e1a1d\"]},{\"id\":\"6baa5514-9a70-4f1f-99a3-8df8f3a7c1c8\",\"name\":\"Math\",\"description\":\"Pre-loaded project Math\",\"defaultId\":\"b2106e40-f0cb-42a0-9080-2493655e7a78\",\"commitIDs\":[\"b2106e40-f0cb-42a0-9080-2493655e7a78\"],\"headIDs\":[\"b2106e40-f0cb-42a0-9080-2493655e7a78\"]},{\"id\":\"f1a1325f-fb0b-47e7-883f-0416872ea3e4\",\"name\":\"Context\",\"description\":\"Pre-loaded project Context\",\"defaultId\":\"0b6702e7-bf3a-4f10-879b-cd445a03f5ed\",\"commitIDs\":[\"0b6702e7-bf3a-4f10-879b-cd445a03f5ed\"],\"headIDs\":[\"0b6702e7-bf3a-4f10-879b-cd445a03f5ed\"]},{\"id\":\"ff58511c-e8dc-42b2-8a97-29ebf38e1d32\",\"name\":\"GenialBusses\",\"description\":\"Pre-loaded project GenialBusses\",\"defaultId\":\"2edbecf1-ed43-4d3f-b616-973c11bf7861\",\"commitIDs\":[\"2edbecf1-ed43-4d3f-b616-973c11bf7861\"],\"headIDs\":[\"2edbecf1-ed43-4d3f-b616-973c11bf7861\"]}]";
        SysMLv2::SysMLv2Deserializer::deserializeJsonArray(jsonString);
        FAIL()<<"Expected Exception!";
    }catch (std::exception& ex) {
        std::cout<<ex.what()<<std::endl;
        EXPECT_EQ(ex.what(),std::string("[json.exception.type_error.302] type must be string, but is null"));
    }
}

// TEST(TestSerilization, TestSerilizationAndDeserialization) {
//     std::string jsonString = "{\n"
//                              "  \"@id\": \"3fa85f64-5717-4562-b3fc-2c963f66afa6\",\n"
//                              "  \"@type\": \"Project\",\n"
//                              "  \"created\": \"2024-02-22T08:58:57.343000000Z\",\n"
//                              "  \"defaultBranch\": {\n"
//                              "    \"@id\": \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"\n"
//                              "  },\n"
//                              "  \"description\": \"string\",\n"
//                              "  \"name\": \"string\"\n"
//                              "}";
//
//     SysMLv2::Entities::Project project = SysMLv2::Entities::Project(jsonString);
//
//     EXPECT_EQ(jsonString,project.serializeToJson());
// }

TEST(TestDeserialization,TestDeserializeMultibleElement) {
    std::string jsonString = "["
                             "  {"
                             "      \"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\","
                             "      \"@type\":\"AnnotatingElement\","
                             "      \"name\":\"Adding Content for the Digital Twin.md\","
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":"
                             "          ["
                             "              {\"@id\":\"f3ed8612-3e5a-40df-8b59-8f98d3b9a4d4\"},"
                             "              {\"@id\":\"d8fe3743-4161-4115-81c3-ebb8273438fd\"},"
                             "              {\"@id\":\"c700555b-6d0c-45d3-8a37-db5a209790fe\"},"
                             "              {\"@id\":\"13cbe0ba-9cc3-4675-834a-d9fa1f0057fd\"},"
                             "              {\"@id\":\"b6b8e029-cef4-4642-bd10-eab4cc4f75e5\"},"
                             "              {\"@id\":\"221e93c4-93a3-4704-af48-2871ec6ffe6b\"},"
                             "              {\"@id\":\"6edc9647-e439-4186-be3f-77f41ccb9b1e\"},"
                             "              {\"@id\":\"da5c02d9-9395-4a42-a27c-57ef0591eca0\"},"
                             "              {\"@id\":\"9d7d2ee9-1878-4fbf-b4a2-bca13ee9909d\"},"
                             "              {\"@id\":\"dc44569e-e398-4862-a5d5-c7f58b9e9d9e\"},"
                             "              {\"@id\":\"41ac9836-7e46-45b8-aad4-749f9daf3d44\"},"
                             "              {\"@id\":\"0c6ebb14-4356-41f5-9c2a-99dae13e4636\"},"
                             "              {\"@id\":\"6ddfa90b-fe26-4894-8ae5-4d34fff212b3\"},"
                             "              {\"@id\":\"7b269e6f-7acf-4926-b38c-ee127c7649aa\"},"
                             "              {\"@id\":\"24214046-a192-4e20-92be-09c097011853\"},"
                             "              {\"@id\":\"f90f3ced-b313-498e-8ab1-fda93c2af922\"},"
                             "              {\"@id\":\"f81a36d2-3d26-4ce4-a2b5-a012fcda4c7e\"},"
                             "              {\"@id\":\"f51e7ccd-c58d-42d6-b290-c0c5743aa0bb\"},"
                             "              {\"@id\":\"a2f70cea-0a1c-41be-9bf3-cb28bd6f5fed\"},"
                             "              {\"@id\":\"c67d4d72-5168-4eb0-a9bd-f85d29156d83\"},"
                             "              {\"@id\":\"9b99d15e-175d-4b6c-a036-49177dbddba8\"},"
                             "              {\"@id\":\"22bc987b-3dc7-4c4b-b9da-0e01f5e5b720\"},"
                             "              {\"@id\":\"c0316132-51bf-4fa8-9707-c08c15521a3f\"},"
                             "              {\"@id\":\"e9d66df1-6f2a-4a0e-b8dd-e15d58e8e6d6\"},"
                             "              {\"@id\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\"}"
                             "          ],"
                             "      \"owner\": {\"@id\":null},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":null,"
                             "      \"body\":\"\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\""
                             "  },"
                             "  {"
                             "      \"@id\":\"f3ed8612-3e5a-40df-8b59-8f98d3b9a4d4\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"YaML\","
                             "      \"body\":\"---\\nusage: SI, ScalarValues\\nname: DTTester4Project\\ndescription: DTTester4Project\\ntitle: DTTester4Project\\nmaintainer: Moritz Herzog\\n---\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"f3ed8612-3e5a-40df-8b59-8f98d3b9a4d4\""
                             "  },"
                             "  {"
                             "      \"@id\":\"d8fe3743-4161-4115-81c3-ebb8273438fd\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"[toc]\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"d8fe3743-4161-4115-81c3-ebb8273438fd\""
                             "  },"
                             "  {"
                             "      \"@id\":\"c700555b-6d0c-45d3-8a37-db5a209790fe\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"# Basic Definitions\\nIn the basic definitions the commands variable, measurable and controllable are defined. These Commands allow us to specify specific digital twin (dt) properties.\\n\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"c700555b-6d0c-45d3-8a37-db5a209790fe\""
                             "  },"
                             "  {"
                             "      \"@id\":\"13cbe0ba-9cc3-4675-834a-d9fa1f0057fd\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Variable\\n**Will be replaced by attribute alone!** A variable displays a variable to the dt, whereas a attribute defined a static value.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"13cbe0ba-9cc3-4675-834a-d9fa1f0057fd\""
                             "  },{"
                             "      \"@id\":\"b6b8e029-cef4-4642-bd10-eab4cc4f75e5\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"#command variable attribute;\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"b6b8e029-cef4-4642-bd10-eab4cc4f75e5\""
                             "  },"
                             "  {"
                             "      \"@id\":\"221e93c4-93a3-4704-af48-2871ec6ffe6b\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Measurable\\nDisplays the dt a value that is measured. A measured value is a value that measured by the physical twin (pt) and streamed to the dt. Allowing the dt to implement functionality and much more.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"221e93c4-93a3-4704-af48-2871ec6ffe6b\""
                             "  },"
                             "  {"
                             "      \"@id\":\"6edc9647-e439-4186-be3f-77f41ccb9b1e\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"#command measurable variable;\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"6edc9647-e439-4186-be3f-77f41ccb9b1e\""
                             "  },"
                             "  {"
                             "      \"@id\":\"da5c02d9-9395-4a42-a27c-57ef0591eca0\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Controllable\\nDisplays the dt a variable that is calculated by the dt and streamed to the pt. The pt has to act accordingly to the value of the variable. This allows for an controll elements of the pt.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"da5c02d9-9395-4a42-a27c-57ef0591eca0\""
                             "  },"
                             "  {"
                             "      \"@id\":\"9d7d2ee9-1878-4fbf-b4a2-bca13ee9909d\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"#command controllable variable; \","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"9d7d2ee9-1878-4fbf-b4a2-bca13ee9909d\""
                             "  },"
                             "  {"
                             "      \"@id\":\"dc44569e-e398-4862-a5d5-c7f58b9e9d9e\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"# Introduction\\nThis represents the example of an bidirectional charger is displayed. This is a really basic implementation of the charger, also parts are missing.\\n\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"dc44569e-e398-4862-a5d5-c7f58b9e9d9e\""
                             "  },"
                             "  {"
                             "      \"@id\":\"41ac9836-7e46-45b8-aad4-749f9daf3d44\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,\"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"# Components\\nIn this section shows all components of the example for the digital twin.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"41ac9836-7e46-45b8-aad4-749f9daf3d44\""
                             "  },"
                             "  {"
                             "      \"@id\":\"0c6ebb14-4356-41f5-9c2a-99dae13e4636\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Cableport\\nThe cable port definition is the definition of a port allowing for the connections between the components. The name stems from the cable, beeing the thing that connects the componets in reality, and the port, beeing the class of SysMLv2 creating the connection option. This allows the dt to implement the communication between the elements.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"0c6ebb14-4356-41f5-9c2a-99dae13e4636\""
                             "  },"
                             "  {"
                             "      \"@id\":\"6ddfa90b-fe26-4894-8ae5-4d34fff212b3\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"port def CablePort {\\n    variable Voltage : Voltage;\\n    variable Current : Current;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"6ddfa90b-fe26-4894-8ae5-4d34fff212b3\""
                             "  },"
                             "  {"
                             "      \"@id\":\"7b269e6f-7acf-4926-b38c-ee127c7649aa\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Grid\\nThe grid part displays the real grid that is part of the systems definition. In the grid we could connect to an alternating current (two phases) or an tree phase current.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"7b269e6f-7acf-4926-b38c-ee127c7649aa\""
                             "  },"
                             "  {"
                             "      \"@id\":\"24214046-a192-4e20-92be-09c097011853\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part Grid {\\n    measurable ACVoltage : Voltage;\\n    port WallOutlet : CablePort;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"24214046-a192-4e20-92be-09c097011853\""
                             "  },"
                             "  {"
                             "      \"@id\":\"f90f3ced-b313-498e-8ab1-fda93c2af922\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Rectifyer\\n\\nThis changes the alternating current to the direct current. This part can eigthe be in the car or in the charging station, dependend on the used standard [[Source](https://en.wikipedia.org/wiki/Charging_station)]. Normally also a n Inverter is needed inside of the model, to allow for the Implementation of the charging of the grid.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"f90f3ced-b313-498e-8ab1-fda93c2af922\""
                             "  },"
                             "  {"
                             "      \"@id\":\"f81a36d2-3d26-4ce4-a2b5-a012fcda4c7e\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part ACDC {\\n    port WallPlug : CablePort;\\n    measurable ACVoltage : Voltage;\\n    measurable DCVoltage : Voltage;\\n    port DCConnection : CablePort;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"f81a36d2-3d26-4ce4-a2b5-a012fcda4c7e\""
                             "  },"
                             "  {"
                             "      \"@id\":\"f51e7ccd-c58d-42d6-b290-c0c5743aa0bb\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## DC-to-DC converter\\n\\nThe dc-to-dc converter allows for the convertion between the voltages.  With having an high voltage side and a low voltage side. The converter needs to convert in both directions, allowing for the bidirectional charging.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"f51e7ccd-c58d-42d6-b290-c0c5743aa0bb\""
                             "  },"
                             "  {"
                             "      \"@id\":\"a2f70cea-0a1c-41be-9bf3-cb28bd6f5fed\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part DCDC {\\n    port HVVoltagePort : CablePort;\\n    measurable HVVoltage : Voltage;\\n    measurable LVVoltage : Voltage;\\n    port LVVoltagePort : CablePort;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"a2f70cea-0a1c-41be-9bf3-cb28bd6f5fed\""
                             "  },"
                             "  {"
                             "      \"@id\":\"c67d4d72-5168-4eb0-a9bd-f85d29156d83\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"\\n## Battery\\n\\nThe battery that is charged and discharged. Normally the battery as a specific side on the dc-dc converter.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"c67d4d72-5168-4eb0-a9bd-f85d29156d83\""
                             "  },"
                             "  {"
                             "      \"@id\":\"9b99d15e-175d-4b6c-a036-49177dbddba8\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part Battery {\\n    port plusVoltage : CablePort;\\n    port referenceVoltage : CablePort;\\n    measurable batteryVoltage : Voltage;\\n    attribute internalResistance : Resistance;\\n    controllable offSwitch : Boolean;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"9b99d15e-175d-4b6c-a036-49177dbddba8\""
                             "  },"
                             "  {"
                             "      \"@id\":\"22bc987b-3dc7-4c4b-b9da-0e01f5e5b720\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"}"
                             "      ,\"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"## Load\\n\\nThe load that is used to display the bidirectinal system side.\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"22bc987b-3dc7-4c4b-b9da-0e01f5e5b720\""
                             "  },"
                             "  {"
                             "      \"@id\":\"c0316132-51bf-4fa8-9707-c08c15521a3f\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part Load {\\n    measurable dCVoltage : Volage;\\n    controllable offSwitch : Boolean;\\n}\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"c0316132-51bf-4fa8-9707-c08c15521a3f\""
                             "  },"
                             "  {"
                             "      \"@id\":\"e9d66df1-6f2a-4a0e-b8dd-e15d58e8e6d6\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"Markdown\","
                             "      \"body\":\"# Complete System\\n\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"e9d66df1-6f2a-4a0e-b8dd-e15d58e8e6d6\""
                             "  },"
                             "  {"
                             "      \"@id\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\","
                             "      \"@type\":\"TextualRepresentation\","
                             "      \"name\":null,"
                             "      \"shortName\":null,"
                             "      \"declaredName\":null,"
                             "      \"declaredShortName\":null,"
                             "      \"ownedElements\":[],"
                             "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                             "      \"owningMembership\":null,"
                             "      \"owningNamespace\":null,"
                             "      \"owningRelationship\":null,"
                             "      \"direction\":null,"
                             "      \"valueStr\":null,"
                             "      \"importedMemberName\":\"null\","
                             "      \"importedNamespace\":\"null\","
                             "      \"language\":\"SysML\","
                             "      \"body\":\"part EVCharger {\\n    part grid : Grid;\\n    part acdc : ACDC;\\n    part dcdc : DCDC;\\n    part battery : Battery;\\n    part load : Load;\\n}\\n\\nEVCharger::grid::ACVoltage connectTo EVCharger::acdc::ACVoltage;\\nEVCharger::acdc::DCVoltage connectTo EVCharger::dcdc::DCVoltageInput;\\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::battery::DCVoltageOutput;\\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::load::DCVoltage;\","
                             "      \"source\":[],"
                             "      \"target\":[],"
                             "      \"isStandard\":null,"
                             "      \"isLibraryElement\":null,"
                             "      \"isImplied\":null,"
                             "      \"isImpliedIncluded\":null,"
                             "      \"documentation\":null,"
                             "      \"textualRepresentation\":null,"
                             "      \"aliasIds\":[],"
                             "      \"elementId\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\""
                             "  }"
                             "]";
    auto elements = SysMLv2::SysMLv2Deserializer::deserializeJsonArray(jsonString);
    EXPECT_EQ(elements.size(),26);
}

TEST(TestDeserialization, AnnotatingElementExample) {
    std::string jsonElement = "  {"
                              "      \"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\","
                              "      \"@type\":\"AnnotatingElement\","
                              "      \"name\":\"Adding Content for the Digital Twin.md\","
                              "      \"shortName\":null,"
                              "      \"declaredName\":null,"
                              "      \"declaredShortName\":null,"
                              "      \"ownedElements\":"
                              "          ["
                              "              {\"@id\":\"f3ed8612-3e5a-40df-8b59-8f98d3b9a4d4\"},"
                              "              {\"@id\":\"d8fe3743-4161-4115-81c3-ebb8273438fd\"},"
                              "              {\"@id\":\"c700555b-6d0c-45d3-8a37-db5a209790fe\"},"
                              "              {\"@id\":\"13cbe0ba-9cc3-4675-834a-d9fa1f0057fd\"},"
                              "              {\"@id\":\"b6b8e029-cef4-4642-bd10-eab4cc4f75e5\"},"
                              "              {\"@id\":\"221e93c4-93a3-4704-af48-2871ec6ffe6b\"},"
                              "              {\"@id\":\"6edc9647-e439-4186-be3f-77f41ccb9b1e\"},"
                              "              {\"@id\":\"da5c02d9-9395-4a42-a27c-57ef0591eca0\"},"
                              "              {\"@id\":\"9d7d2ee9-1878-4fbf-b4a2-bca13ee9909d\"},"
                              "              {\"@id\":\"dc44569e-e398-4862-a5d5-c7f58b9e9d9e\"},"
                              "              {\"@id\":\"41ac9836-7e46-45b8-aad4-749f9daf3d44\"},"
                              "              {\"@id\":\"0c6ebb14-4356-41f5-9c2a-99dae13e4636\"},"
                              "              {\"@id\":\"6ddfa90b-fe26-4894-8ae5-4d34fff212b3\"},"
                              "              {\"@id\":\"7b269e6f-7acf-4926-b38c-ee127c7649aa\"},"
                              "              {\"@id\":\"24214046-a192-4e20-92be-09c097011853\"},"
                              "              {\"@id\":\"f90f3ced-b313-498e-8ab1-fda93c2af922\"},"
                              "              {\"@id\":\"f81a36d2-3d26-4ce4-a2b5-a012fcda4c7e\"},"
                              "              {\"@id\":\"f51e7ccd-c58d-42d6-b290-c0c5743aa0bb\"},"
                              "              {\"@id\":\"a2f70cea-0a1c-41be-9bf3-cb28bd6f5fed\"},"
                              "              {\"@id\":\"c67d4d72-5168-4eb0-a9bd-f85d29156d83\"},"
                              "              {\"@id\":\"9b99d15e-175d-4b6c-a036-49177dbddba8\"},"
                              "              {\"@id\":\"22bc987b-3dc7-4c4b-b9da-0e01f5e5b720\"},"
                              "              {\"@id\":\"c0316132-51bf-4fa8-9707-c08c15521a3f\"},"
                              "              {\"@id\":\"e9d66df1-6f2a-4a0e-b8dd-e15d58e8e6d6\"},"
                              "              {\"@id\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\"}"
                              "          ],"
                              "      \"owner\": {\"@id\":null},"
                              "      \"owningMembership\":null,"
                              "      \"owningNamespace\":null,"
                              "      \"owningRelationship\":null,"
                              "      \"direction\":null,"
                              "      \"valueStr\":null,"
                              "      \"importedMemberName\":\"null\","
                              "      \"importedNamespace\":\"null\","
                              "      \"language\":null,"
                              "      \"body\":\"\","
                              "      \"source\":[],"
                              "      \"target\":[],"
                              "      \"isStandard\":null,"
                              "      \"isLibraryElement\":null,"
                              "      \"isImplied\":null,"
                              "      \"isImpliedIncluded\":null,"
                              "      \"documentation\":null,"
                              "      \"textualRepresentation\":null,"
                              "      \"aliasIds\":[],"
                              "      \"elementId\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\""
                              "  }";
    auto entity = SysMLv2::SysMLv2Deserializer::deserializeJsonString(jsonElement);
    EXPECT_TRUE(entity!=NULL);
    if(entity!=NULL) {
        auto element = dynamic_cast<SysMLv2::Entities::Element *>(entity);
        EXPECT_EQ(boost::lexical_cast<std::string>(element->getId()), "10aac60e-3f21-467e-90c4-32bedb1f8738");
        EXPECT_EQ(element->ownedElements().size(), 25);
    }
}

TEST(TestDeserialization, TextualRepresentation) {
    std::string jsonElement = "  {"
                              "      \"@id\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\","
                              "      \"@type\":\"TextualRepresentation\","
                                                           "      \"name\":null,"
                                                           "      \"shortName\":null,"
                                                           "      \"declaredName\":null,"
                                                           "      \"declaredShortName\":null,"
                                                           "      \"ownedElements\":[],"
                                                           "      \"owner\":{\"@id\":\"10aac60e-3f21-467e-90c4-32bedb1f8738\"},"
                                                           "      \"owningMembership\":null,"
                                                           "      \"owningNamespace\":null,"
                                                           "      \"owningRelationship\":null,"
                                                           "      \"direction\":null,"
                                                           "      \"valueStr\":null,"
                                                           "      \"importedMemberName\":\"null\","
                                                           "      \"importedNamespace\":\"null\","
                                                           "      \"language\":\"SysML\","
                                                           "      \"body\":\"part EVCharger {\\n    part grid : Grid;\\n    part acdc : ACDC;\\n    part dcdc : DCDC;\\n    part battery : Battery;\\n    part load : Load;\\n}\\n\\nEVCharger::grid::ACVoltage connectTo EVCharger::acdc::ACVoltage;\\nEVCharger::acdc::DCVoltage connectTo EVCharger::dcdc::DCVoltageInput;\\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::battery::DCVoltageOutput;\\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::load::DCVoltage;\","
                                                           "      \"source\":[],"
                                                           "      \"target\":[],"
                                                           "      \"isStandard\":null,"
                                                           "      \"isLibraryElement\":null,"
                                                           "      \"isImplied\":null,"
                                                           "      \"isImpliedIncluded\":null,"
                                                           "      \"documentation\":null,"
                                                           "      \"textualRepresentation\":null,"
                                                           "      \"aliasIds\":[],"
                                                           "      \"elementId\":\"bc3472ef-d3d4-46c3-9702-ae53a0265f54\""
                                                           "  }";
    auto entity = SysMLv2::SysMLv2Deserializer::deserializeJsonString(jsonElement);
    EXPECT_TRUE(entity!=NULL);
    if(entity!=NULL) {
        auto element = dynamic_cast<SysMLv2::Entities::Element *>(entity);
        EXPECT_EQ(boost::lexical_cast<std::string>(element->getId()), "bc3472ef-d3d4-46c3-9702-ae53a0265f54");
        EXPECT_EQ(boost::lexical_cast<std::string>(element->owner()->getID()),"10aac60e-3f21-467e-90c4-32bedb1f8738");
        EXPECT_EQ(element->body(), "part EVCharger {\n    part grid : Grid;\n    part acdc : ACDC;\n    part dcdc : DCDC;\n    part battery : Battery;\n    part load : Load;\n}\n\nEVCharger::grid::ACVoltage connectTo EVCharger::acdc::ACVoltage;\nEVCharger::acdc::DCVoltage connectTo EVCharger::dcdc::DCVoltageInput;\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::battery::DCVoltageOutput;\nEVCharger::dcdc::DCVoltageOutput connectTo EVCharger::load::DCVoltage;");
    }
}

